LOAD DATA LOCAL INFILE '%SQL_DATA_DIRECTORY%zip_code.csv'
INTO TABLE zip_code
FIELDS
  TERMINATED BY ','
  ENCLOSED BY ''
  ESCAPED BY '\\'
LINES
  STARTING BY ''
  TERMINATED BY '\n'
IGNORE 1 LINES;
